version: '2'
services: 
    elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
       environment:
          - "discovery.type=single-node"
          - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
          - "xpack.license.self_generated.type=basic"
       ports:
          - 9200:9200
          - 9300:9300
       user: "elasticsearch"


    kibana:
       image: docker.elastic.co/kibana/kibana:7.6.0
       ports:
          - 5601:5601
       environment:
          - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
       depends_on:
          - elasticsearch
       command:
          - /usr/share/kibana/bin/kibana
    